export const GET_WEATHER_CITY = 'GET_WEATHER_CITY';
export const GET_WEATHER_NAVIGATOR = 'GET_WEATHER_NAVIGATOR';
export const GET_WEATHER_DAILY = 'GET_WEATHER_DAILY';
export const GET_WEATHER_HOURLY = 'GET_WEATHER_HOURLY';

export const GET_CURRENT_LOCATION_REQUESTED = 'GET_CURRENT_LOCATION_REQUESTED';
export const GET_CURRENT_LOCATION_SUCCEEDED = 'GET_CURRENT_LOCATION_SUCCEEDED';
export const GET_CURRENT_LOCATION_FAILED = 'GET_CURRENT_LOCATION_FAILED';
