export const GET_WEATHER_CITY = 'GET_WEATHER_CITY';
export const GET_WEATHER_NAVIGATOR = 'GET_WEATHER_NAVIGATOR';
export const GET_WEATHER_DAILY = 'GET_WEATHER_DAILY';
export const GET_WEATHER_HOURLY = 'GET_WEATHER_HOURLY';

export const GET_CURRENT_LOCATION_REQUESTED = 'GET_CURRENT_LOCATION_REQUESTED';
export const GET_CURRENT_LOCATION_SUCCEEDED = 'GET_CURRENT_LOCATION_SUCCEEDED';
export const GET_CURRENT_LOCATION_FAILED = 'GET_CURRENT_LOCATION_FAILED';

// WEATHER

export const URL_WEATHER = 'https://api.openweathermap.org/data/2.5/';
export const API_KEY = 'ca92d5d554730b0689860ca54b0d5b7f';

export const FETCH_USERS = 'FETCH_USERS';
