export const AUTO_COMPLETE_URL = `https://dataservice.accuweather.com/locations/v1/cities/autocomplete?apikey=${process.env.REACT_APP_ACCUWEATHER_KEY}&q=`;

export const GET_CURRENT_LOCATION_REQUESTED = 'GET_CURRENT_LOCATION_REQUESTED';
export const ASYNC_FETCH_WEATHER_DATA_GEOLOCATION_BAN =
  'ASYNC_FETCH_WEATHER_DATA_GEOLOCATION_BAN';

export const GET_CURRENT_LOCATION_FAILED = 'GET_CURRENT_LOCATION_FAILED';
export const today = new Date();
// API
export const REACT_APP_OPENWEATHER_URL =
  'https://api.openweathermap.org/data/2.5/weather?';

// WEATHER

export const URL_WEATHER = 'https://api.openweathermap.org/data/2.5/';
export const URL_WEATHERBIT = 'https://api.weatherbit.io/v2.0/forecast/';
export const API_KEY = 'ca92d5d554730b0689860ca54b0d5b7f';

export const ASYNC_FETCH_WEATHER_SEARCH_DATA_SYS =
  'ASYNC_FETCH_WEATHER_SEARCH_DATA_SYS';
export const ASYNC_FETCH_WEATHER_SEARCH_DATA_CITY =
  'ASYNC_FETCH_WEATHER_SEARCH_DATA_CITY';
export const ASYNC_FETCH_WEATHER_SEARCH_DATA_TEMP =
  'ASYNC_FETCH_WEATHER_SEARCH_DATA_TEMP';
export const ASYNC_FETCH_WEATHER_SEARCH_DATA_IMG =
  'ASYNC_FETCH_WEATHER_SEARCH_DATA_IMG';
export const ASYNC_FETCH_WEATHER_SEARCH_DAILY =
  'ASYNC_FETCH_WEATHER_SEARCH_DAILY';
export const ASYNC_FETCH_WEATHER_SEARCH_HOURLY =
  'ASYNC_FETCH_WEATHER_SEARCH_HOURLY';
export const ASYNC_FETCH_WEATHER_SEARCH_NAME_WEATHER =
  'ASYNC_FETCH_WEATHER_SEARCH_NAME_WEATHER';
export const GET_CURRENT_WEATHER_DATA_SUCCEEDED =
  'GET_CURRENT_WEATHER_DATA_SUCCEEDED';
export const ASYNC_FETCH_WEATHER_DATA = 'ASYNC_FETCH_WEATHER_DATA';

// weather hourly and daily
export const FETCH_WEEKLY_WEATHER = 'FETCH_WEEKLY_WEATHER';
export const FETCH_WEEKLY_WEATHER_SUCCESS = 'FETCH_WEEKLY_WEATHER_SUCCESS';
export const FETCH_HOURLY_WEATHER_SUCCESS = 'FETCH_HOURLY_WEATHER_SUCCESS';
